Kpmp 2707 rolling bootes into explorer
KPMP/pegasus-web pull request #147
Opened 2021-05-28 22:01 UTC by abarkellumich

2021-06-01 20:13 UTC, rlreamy requested changes

2021-06-01 20:13 UTC, rlreamy commented on package.json
> +    "plotly.js": "^1.58.4",
I thought we were using our kpmp-custom-plotly

2021-06-01 20:13 UTC, rlreamy commented on src/App.js
> +                <Route path='/explorer/dataViz' component={RNASeqVizContainer} store={store} />
This was true before, but some of these routes are exact, and some are not...we should discuss with @zwright 
 whether they can all be exact or not. I think they can.

2021-06-01 20:13 UTC, rlreamy commented on src/initialState.json
> +  "summary": [
Do we need all of this in initial state still? Or can some of this be cleaned out?

2021-06-01 20:17 UTC, abarkellumich commented on package.json
> +    "plotly.js": "^1.58.4",
Forgot about the custom module, yes, we should use that instead of this, will update

2021-06-01 20:21 UTC, abarkellumich commented on src/App.js
> +                <Route path='/explorer/dataViz' component={RNASeqVizContainer} store={store} />
FWIW, I was able to, locally, navigate to each route using the in-app routing, and through navigating directly via the URL

2021-06-01 20:25 UTC, abarkellumich commented on src/initialState.json
> +  "summary": [
We will need some of it, in particular the data counts for the summary data, until this turns into real data fetches. But yeah, I think the removal of the dataTypeByParticipant is all worth tossing. That data was being used in a graph that is no longer present

2021-06-02 17:51 UTC, rlreamy approved these changes

2021-06-02 17:51 UTC, merged