KPMP-3222-Back-to-home-button-should-go-somewhere-else-from-Atlas-Homepage
KPMP/pegasus-web pull request #288
Opened 2021-11-05 15:58 UTC by abarkellumich

2021-11-05 17:37 UTC, rlreamy requested changes

2021-11-05 17:37 UTC, rlreamy commented on src/components/Error/NotFoundPage.js
> +
can't we just do something like this:
${window.location.pathname.replaceAll("/", "") === 'explorer'
and send them to explorer and 
${window.location.pathname.replaceAll("/", "") === ''
and send them to the Atlas home page?

2021-11-05 17:37 UTC, rlreamy commented on src/components/Error/NotFoundPage.js
> +
This is what we are doing in the Nav to determine which item to highlight

2021-11-05 21:52 UTC, abarkellumich commented on src/components/Error/NotFoundPage.js
> +
Great questions, hopefully, I can clear them up!

On doing:
>${window.location.pathname.replaceAll("/", "") === 'explorer'

There are a couple of problems I saw with this approach, and why I avoided it for indexOf. Firstly, we would need to upgrade to v15 for replaceAll (there are of course other ways to do a replace all though, just not as elegant, older js solutions for this get confusing fast). The second issue I was attempting to avoid was a potential future namespace collision. For example '/foo/explorer' may not be the same as '/explorer/', thought it would be better to try avoid this potential (I do admit it's a rare possibility). Thirdly, the === portion would require an exact match to '/explorer', and would then have to handle the edge case somehow for '/explorer/foo' (the result would be 'explorerfoo' === 'explorer' and fail). This is what spawned the line of code below:

`pathname.split('/')[1].indexOf(expectedPath) >=0`

It's expecting the window.location.pathname, so we're the same there, but I force the splits on '/' to specifically grab that first subpath. I do this so I don't have to worry about the /foo portion becoming explorerfoo.  At this point, yes the === would work ( if the path was say '/explorer/foo', the pathname.split("/")[1] would give us just 'explorer'), but I think the .indexOf is superior because it captures the same intent as === but also accounts for potential typos. For example, explorerer would still capture as 'explorer' with the indexOf, but NOT with the ===. This works fine with the Nav because it needs to explicitly be /explorer to be on the /explorer route. With a not found page, this may not be true. Thinking of the explorerer example again, this typo would correctly bring the user to the not-found page (we have no route by that name) but the intent is capturable(they got the majority of the word there!), the user _wanted_ /explorer, so we give them the /explorer route instead of /.

I also went with pathname, and more broadly speaking, this aspect as function, rather than window.location.pathname inside of the unbutton click for a couple of reasons. Firstly, by having this as a function, I was able to write simple unit tests for it. This accomplishes Becky S' goal of having more things tested to hopefully avoid multiple rounds of QA, and also allows us to have a better confirmation that the code works. I think it also keeps the render function a bit cleaner, the less logic inside of the HTML, the less difficult it is to parse when a page grows. So, with the idea of having this as a function, we could still do window.location.pathname, but the problem is then that this function isn't repeatable. If instead, we ask the caller to pass the variable in as a parameter to the function, we can keep it atomic and repeatable for the tests. As a byproduct, this keeps it more simple to reason about, we don't have to worry about the application running, just the inputs and outputs of this function. 

The most complex aspect of this PR in my opinion is the fuzzyPathErrors. This isn't explicitly needed, but is a nice small feature to assist the user when they fumble the url. Much the same problem with the ===, the indexOf suffers a similar problem in that it does require the complete substring to match. So, /explore/foo would fail to match with IndexOf. The objective of FuzzyPathErrors is to capture that user intent, and correct it for them. Yes, /explore will fail, but we can at least give the user the correct route on the not-found page.

There are two more benefits of this solution being written as functions. First, the fuzzyPathErrors can be used elsewhere as a simple fuzzyFinder, eg. If in the future we wanted to autocorrect a user mistake of /explore, and route them to /explorer without an error page, we could do so easily. Second, because of this simply being composed of functions, it is trivially easy to remove! If we don't like it, no biggie.

2021-11-09 14:43 UTC, rlreamy approved these changes

2021-11-09 15:08 UTC, merged